// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.1
// source: cjson/pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Template) Reset() {
	*x = Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjson_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_cjson_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_cjson_pb_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RawValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to TestOneof:
	//
	//	*RawValue_Str
	//	*RawValue_Bool
	//	*RawValue_NumberDouble
	//	*RawValue_NumberInt32
	TestOneof isRawValue_TestOneof `protobuf_oneof:"test_oneof"`
}

func (x *RawValue) Reset() {
	*x = RawValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjson_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawValue) ProtoMessage() {}

func (x *RawValue) ProtoReflect() protoreflect.Message {
	mi := &file_cjson_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawValue.ProtoReflect.Descriptor instead.
func (*RawValue) Descriptor() ([]byte, []int) {
	return file_cjson_pb_proto_rawDescGZIP(), []int{1}
}

func (m *RawValue) GetTestOneof() isRawValue_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *RawValue) GetStr() string {
	if x, ok := x.GetTestOneof().(*RawValue_Str); ok {
		return x.Str
	}
	return ""
}

func (x *RawValue) GetBool() bool {
	if x, ok := x.GetTestOneof().(*RawValue_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *RawValue) GetNumberDouble() float64 {
	if x, ok := x.GetTestOneof().(*RawValue_NumberDouble); ok {
		return x.NumberDouble
	}
	return 0
}

func (x *RawValue) GetNumberInt32() int32 {
	if x, ok := x.GetTestOneof().(*RawValue_NumberInt32); ok {
		return x.NumberInt32
	}
	return 0
}

type isRawValue_TestOneof interface {
	isRawValue_TestOneof()
}

type RawValue_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type RawValue_Bool struct {
	Bool bool `protobuf:"varint,2,opt,name=bool,proto3,oneof"`
}

type RawValue_NumberDouble struct {
	NumberDouble float64 `protobuf:"fixed64,3,opt,name=number_double,json=numberDouble,proto3,oneof"`
}

type RawValue_NumberInt32 struct {
	NumberInt32 int32 `protobuf:"varint,4,opt,name=number_int32,json=numberInt32,proto3,oneof"`
}

func (*RawValue_Str) isRawValue_TestOneof() {}

func (*RawValue_Bool) isRawValue_TestOneof() {}

func (*RawValue_NumberDouble) isRawValue_TestOneof() {}

func (*RawValue_NumberInt32) isRawValue_TestOneof() {}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsArr        bool      `protobuf:"varint,1,opt,name=isArr,proto3" json:"isArr,omitempty"`
	TemplateHash []byte    `protobuf:"bytes,2,opt,name=templateHash,proto3" json:"templateHash,omitempty"`
	Items        []*Item   `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	RawValue     *RawValue `protobuf:"bytes,4,opt,name=rawValue,proto3" json:"rawValue,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cjson_pb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_cjson_pb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_cjson_pb_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetIsArr() bool {
	if x != nil {
		return x.IsArr
	}
	return false
}

func (x *Item) GetTemplateHash() []byte {
	if x != nil {
		return x.TemplateHash
	}
	return nil
}

func (x *Item) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Item) GetRawValue() *RawValue {
	if x != nil {
		return x.RawValue
	}
	return nil
}

var File_cjson_pb_proto protoreflect.FileDescriptor

var file_cjson_pb_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6a, 0x73, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x22, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x08, 0x52, 0x61, 0x77, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x25, 0x0a, 0x0d, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x42, 0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x84, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x73, 0x41, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69,
	0x73, 0x41, 0x72, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x61, 0x77, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x08, 0x72, 0x61, 0x77, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x05, 0x5a, 0x03,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cjson_pb_proto_rawDescOnce sync.Once
	file_cjson_pb_proto_rawDescData = file_cjson_pb_proto_rawDesc
)

func file_cjson_pb_proto_rawDescGZIP() []byte {
	file_cjson_pb_proto_rawDescOnce.Do(func() {
		file_cjson_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_cjson_pb_proto_rawDescData)
	})
	return file_cjson_pb_proto_rawDescData
}

var file_cjson_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cjson_pb_proto_goTypes = []interface{}{
	(*Template)(nil), // 0: Template
	(*RawValue)(nil), // 1: RawValue
	(*Item)(nil),     // 2: Item
}
var file_cjson_pb_proto_depIdxs = []int32{
	2, // 0: Item.items:type_name -> Item
	1, // 1: Item.rawValue:type_name -> RawValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cjson_pb_proto_init() }
func file_cjson_pb_proto_init() {
	if File_cjson_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cjson_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjson_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cjson_pb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cjson_pb_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*RawValue_Str)(nil),
		(*RawValue_Bool)(nil),
		(*RawValue_NumberDouble)(nil),
		(*RawValue_NumberInt32)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cjson_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cjson_pb_proto_goTypes,
		DependencyIndexes: file_cjson_pb_proto_depIdxs,
		MessageInfos:      file_cjson_pb_proto_msgTypes,
	}.Build()
	File_cjson_pb_proto = out.File
	file_cjson_pb_proto_rawDesc = nil
	file_cjson_pb_proto_goTypes = nil
	file_cjson_pb_proto_depIdxs = nil
}
